name: Assign issue to contributor
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
  push:
    

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  assign-issue-to-user:
    name: Assign to user
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to user
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          assignees: ${{ github.actor }}
          numOfAssignee: 1
          allowSelfAssign: true
          abortIfPreviousAssignees: true