name: Auto Comment
on:
  issues:
    types:
      - opened
  push:
    

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: https://github.com/GuiWar/github-actions-course/issues/44
        run: |
          gh issue edit https://github.com/GuiWar/github-actions-course/issues/44 --add-assignee "@me"